### **Array**
- Array python ke ander data structure/container /collection hai.
- jisme koi bhi type ki value ho but wo sari values ek hi jaisi type ki honi chaiye.
- it is 3rd party container that stores similar values
- there is 3rd party package named **numpy** and numpy provides implementation of array.
- **numpy**---2005
    - numpy package also provides functions/methods related to descriptive(summary,relationship,visualization) statistics, matrx and other linear alzebra.
    - numpy package was first introduced in **2005** by **Travis Oliphant.**
    

In [1]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

#### numpy me **array** ko create krna:------>array banane ke kai tarike hote hai------->we are going to study minimum 10 way.

#### 1st tarika numpy me array banane ke liye;
    - in coding, array is represented by an object of ndarray class

In [16]:
#integer type
a=np.array([1,2,3,4])
print(type(a))           #class 'numpy.ndarray

<class 'numpy.ndarray'>


In [17]:
print(a)

[1 2 3 4]


In [10]:
#this is list
print([1,2,3,'a'])

[1, 2, 3, 'a']


In [20]:
#integer type me ydi hum float ki ek bhi value likh de do wo sbko float me convert kr dega
a=np.array([1,2,3,4,5.5,])
print(a)          #class 'numpy.ndarray

[1.  2.  3.  4.  5.5]


In [21]:
#integer type me ydi hum float aur koi string value likh de to wo sari value ko string bana dega
a=np.array([1,2,3,4,5.5,'hi'])
print(a)          #class 'numpy.ndarray

['1' '2' '3' '4' '5.5' 'hi']


- **dtype= data tpye-----jo ki hume array me batana padta hai taki jis tpye ki value hum chahte hai array se , wo hume la ke de dega.**
- formula= **-(2) ki power n-1** to **(2) ki power n-1 minus 1** ------->ye formula sirf integer ke sath chalta hai.
    - np.int8-----------        np.float8
    - np.int16----------       np.float16
    - np.int32----------       np.float32
    - np.int64----------       np.float64
    - np.uint8-----------unsinged me negetive value allowed nhi hoti-----0 se 255------------------->jaise [-1,-2]  127+128=255, -2 hone pe 154
    - np.uint16
    - np.uint32
    - np.uint64

In [43]:
#integer type me ydi hum koi float value likh de aur tb per bhi hum pure array ko integer hi banana chahte-------to hume array me datatype batana padta hai.
a=np.array([1,2,3,4,5.5],dtype='int8')
print(a)          #class 'numpy.ndarray

[1 2 3 4 5]


- **circuller round**

In [45]:
#integer type me ydi hum koi float value likh de aur tb per bhi hum pure array ko integer hi banana chahte-------to hume array me datatype batana padta hai.
a=np.array([1,2,3,4,5.5,-1,-2,130,131],dtype='int8')     #circuller round kr diya
print(a)          #class 'numpy.ndarray

[   1    2    3    4    5   -1   -2 -126 -125]


In [47]:
#integer type me ydi hum koi float value likh de aur tb per bhi hum pure array ko integer hi banana chahte-------to hume array me datatype batana padta hai.
a=np.array([1,2,3,4,5.5,-1,-2,-130,131],dtype='uint8')     #circuller round kr diya
print(a)          #class 'numpy.ndarray

[  1   2   3   4   5 255 254 126 131]


In [63]:
a=np.array([1,2,3,6,5,4,5.5],dtype="float16")
print(a)

[1.  2.  3.  6.  5.  4.  5.5]


In [57]:
a=np.array([1,2,3,6,5,4,5.5,'hi'],dtype="float16")      #ValueError could not convert string to float: 'hi'
print(a)

ValueError: could not convert string to float: 'hi'

#### 2. array banane ka 2nd tarika

In [68]:
a=np.arange(1,20,2)       #start,end,step
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [69]:
a=np.arange(20)       #start,end,step-----------default start is 0 ------default step is 1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [73]:
a=np.arange(1,20,0.5)       #start,end,step-----------default start is 0 ------default step is 1
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [75]:
a=np.arange(1,20,.5)       #start,end,step-----------default start is 0 ------default step is 1
print(a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [76]:
a=np.arange(20,0.5)       #start,end,step-----------default start is 0 ------default step is 1
print(a)

[]


- **Difference between list and arange** for getsizeof
    - memory consumption is high in list
    - memory consumption is low in array

In [88]:
x=(list(range(5000)))     #ye puri value dikhata hai
#print(x)

In [91]:
y=np.arange(5000)     #ye puri value nhi dikhata hai, values ko short me dikhata hai.
print(y)

[   0    1    2 ... 4997 4998 4999]


In [89]:
#memory consumption check krne ke liye
import sys

In [92]:
print(sys.getsizeof(x))
print(sys.getsizeof(y))      #getsizeof ye bytes me aate hai.

40056
20112


- **broadcasting between list and arange**   ---------broadcasting ka example **whatapps group**

In [93]:
x=[1000,2000,3000,4000,5000]
print(x)

[1000, 2000, 3000, 4000, 5000]


In [94]:
x=x+500
print(x)      #yha list me broadcasting nhi hota hai.

TypeError: can only concatenate list (not "int") to list

In [95]:
y=[1000,2000,3000,4000,5000]
print(y)

[1000, 2000, 3000, 4000, 5000]


In [98]:
y=np.array([1000,2000,3000,4000,5000])
print(y)

[1000 2000 3000 4000 5000]


In [99]:
y=y+500
print(y)     #yha pe broadcasting wala concept chal jatia hai.

[1500 2500 3500 4500 5500]


- **support int indexing in list** and **support int & boolean(indexing AND CONDITION wali baat ho rhi hai.) indexing in array**

In [101]:
x=[1000,2000,3000,4000,5000]
print(x)

[1000, 2000, 3000, 4000, 5000]


In [102]:
x[-1]

5000

In [103]:
y=np.array([1000,2000,3000,4000,5000])
print(y)

[1000 2000 3000 4000 5000]


In [105]:
y[-1]

5000

In [107]:
print(y[y>=5000])

[5000]


In [108]:
print(x[x>=5000])

TypeError: '>=' not supported between instances of 'list' and 'int'

#### 3. **array banane ka 3rd tarika**------with zeros function

In [2]:
a=np.zeros(5)
print(a)          #by default float considerd kr leta hai.

[0. 0. 0. 0. 0.]


In [5]:
a[0]=5
a[-1]=500
print(a)       #isme indexing ho jati jati hai.-------mutable

[  5.   0.   0.   0. 500.]


#### 4. **array banane ka 4th tarika**------with ones function

In [7]:
o=np.ones(5)
print(o)                  #ones function me hume 1 vlaue hi milti hai.-ye bhi mutable hai----modifiable hai.

[1. 1. 1. 1. 1.]


In [8]:
o[0]=6
o[-1]=200
print(o)

[  6.   1.   1.   1. 200.]


#### 5. **array banane ka 5th tarika**------with full function

In [17]:
f=np.full(5,50000.555)       #(size, intial_value)
print(f)

[50000.555 50000.555 50000.555 50000.555 50000.555]


In [15]:
f[0]=60000
f[-1]=35000
print(f)           #full function bhi mutable and modifiable hota hai. 

[60000 50000 50000 50000 35000]


In [14]:
d=np.full((2,2), [10])
print(d)

[[10 10]
 [10 10]]


#### 6. **array banane ka 6th tarika**------with linspace function
- ye start aur end me jo bhi , ydi hum use size me convert krna chahte hai wo size wise bat kr de deta hai.

In [19]:
l=np.linspace(1,10,6)       #low(first),high(last-inclusive),size
print(l)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [20]:
l=np.linspace(1,1000,5)       #low(first),high(last-inclusive),size
print(l)

[   1.    250.75  500.5   750.25 1000.  ]


In [21]:
l=np.linspace(1,10)       #low(first),high(last-inclusive),size -------default size ki value 50 hoti hai.
print(l)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [22]:
import random

#### 7. **array banane ka 7th tarika**------with sub module random.randint 

In [32]:
a=np.random.randint(1,15,7)        #low,high,size(jitni value hume chaiye)
print(a)
print(type(a))

[ 9  4 11 11  9  2  9]
<class 'numpy.ndarray'>


In [33]:
a=np.random.uniform(3,55,20)      #bydefault floating value hi generate krta hai.
print(a)

[32.4630982  28.3215948  20.60924755 11.83855878 38.73495725 22.9248895
 38.53872232  8.09605558 28.54610568 42.45236198 52.59538291 54.50284605
 23.49445491 22.19662833 23.54472831 15.88219613 15.43947516 15.92815653
 47.59940104 16.23271906]
