#### **Terminology related to numpy array**
- function-------->**np.funname(array)**
- method---------->**array.methodname()**
- property-------->**array.property**

- PROPERTY
    - array.ndim
    

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,10,(3,4))
print(a)

[[5 3 4 8]
 [5 5 5 2]
 [2 3 8 8]]


- **axix=0 krne per column wise sum krta hai ye**

#method ke sath plus krne per
print(a.sum(),a.sum(axis=0))      

- **axix=1 krne per row wise sum krta hai ye**

In [9]:
#method ke sath plus krne per
print(a.sum(),a.sum(axis=1))      

58 [20 17 21]


- **pure matrix me sbse bada element pata krna ho to**

In [10]:
print(a.max())

8


- **pure matrix ke column aur row me sbse bada element kon hai.**

In [13]:
print(a.max(axis=0))    #column wise
print(a.max(axis=1))    #row wise

[5 5 8 8]
[8 5 8]


- **pure matrix ke column aur row me sbse bada element kon hai.**----iske index nikalna

In [15]:
print(a.argmax())
print(a.argmin())      #internally flentten kr krne ke bad uska index nikalte hai.

3
7


#### **flatten method**
    - a.flatten()

In [16]:
print(a.flatten())    #bydefault order='c' ------row le liya hai.

[5 3 4 8 5 5 5 2 2 3 8 8]


In [18]:
print(a.flatten(order='f'))    #bydefault order='c' ------row le liya hai.

[5 5 2 3 5 3 4 5 8 8 2 8]


In [20]:
#isme order='f' nhi ho rha hai.--------bydefault order='c' wala hi le rha hai.
print(a.argmax())
print(a.argmin())      #internally fletten krne ke bad uska index nikalte hai.

3
7


- **square method** -----square method nhi chalta hai 
    - **NOTE** : square function chalta hai.

In [23]:
print(a.square())

AttributeError: 'numpy.ndarray' object has no attribute 'square'

In [24]:
print(np.square(a))

[[25  9 16 64]
 [25 25 25  4]
 [ 4  9 64 64]]


In [25]:
print(a.squeeze())

[[5 3 4 8]
 [5 5 5 2]
 [2 3 8 8]]


- **matrix pe airthmetic ka broadcasting ho jata hai.**

In [26]:
print(a)

[[5 3 4 8]
 [5 5 5 2]
 [2 3 8 8]]


In [27]:
b=a+500
print(b)

[[505 503 504 508]
 [505 505 505 502]
 [502 503 508 508]]


In [28]:
c=a*5
print(c)

[[25 15 20 40]
 [25 25 25 10]
 [10 15 40 40]]


- **ek matrix ka dusre matrix se operation krne per**

In [29]:
print(a)
print(b)

[[5 3 4 8]
 [5 5 5 2]
 [2 3 8 8]]
[[505 503 504 508]
 [505 505 505 502]
 [502 503 508 508]]


In [30]:
e=a+b
print(e)

[[510 506 508 516]
 [510 510 510 504]
 [504 506 516 516]]


In [31]:
f=a*b
print(f)

[[2525 1509 2016 4064]
 [2525 2525 2525 1004]
 [1004 1509 4064 4064]]


In [37]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [32]:
g=a/b
print(g)

[[0.00990099 0.00596421 0.00793651 0.01574803]
 [0.00990099 0.00990099 0.00990099 0.00398406]
 [0.00398406 0.00596421 0.01574803 0.01574803]]


- MATRIX ME **DOT PRODUCT**
    - jb hum dot product krte hai to , matrix ka size same hona chaiye------like-----(3,3)  or  (4,4)
    - (3,4)(3,4) IS WRONG
    - (3,4)(4,5) IS RIGHT-----PHLE KA COLUMN AUR DUSRE KA ROW SAME HONA CHAIYE

In [36]:
f@g

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [44]:
a=np.random.randint(1,15,(3,3))
b=np.random.randint(1,15,(3,3))
print(a)
print(b)

[[ 3 11  4]
 [12 10  5]
 [13  8 10]]
[[ 8  8  8]
 [14  6 12]
 [14  4  9]]


In [45]:
a@b

array([[234, 106, 192],
       [306, 176, 261],
       [356, 192, 290]])