### **Numpy 3d Array** 
    - array of 2d arrays
    - use to represent color images

In [2]:
import numpy as np

In [5]:
a=np.random.randint(1,10,(3,3))
print(a)

[[7 3 5]
 [2 2 1]
 [8 8 3]]


In [6]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


- **(2,4,4)** 2 is len of 3d array , 4 and 4 is row and column

In [7]:
d=np.random.randint(5,50,(2,4,4))     #(2,4,4) 2 is len of 3d array , 4 and 4 is row and column
print(d)
print(d.ndim)

[[[49 28 23 21]
  [35 22 30 43]
  [18 33 10 43]
  [ 5 20 18 43]]

 [[27 30 29 28]
  [20  5  9 22]
  [ 7 22 41 19]
  [40 19 11 40]]]
3


In [8]:
d=np.random.randint(5,50,(2,3,4,4))     #(2,4,4) 2 is len of 4d array , 4 and 4 is row and column
print(d)
print(d.ndim)

[[[[ 9 23 14 11]
   [26 38 18 28]
   [ 6 36 41 44]
   [15 26 27 40]]

  [[36 23 34 16]
   [24 19 48 40]
   [21  7  6 26]
   [40 36 34  6]]

  [[43 32 45 45]
   [10 23 14 22]
   [33 34 25 48]
   [17  6 12 30]]]


 [[[31 26 31 43]
   [26 41 47 11]
   [ 9 21  9 32]
   [20 39 24 45]]

  [[ 8 41 29 33]
   [13 23  8 37]
   [ 7 46 37 26]
   [30 14 31 44]]

  [[12 44 49  6]
   [ 5 12 46 26]
   [24 44 14  6]
   [30  5 23  7]]]]
4


### **Array Concatenation**

In [9]:
a=np.random.randint(1,10,(5))     #this is one D array
b=np.random.randint(1,10,(5))
print(a)
print(b)

[2 7 7 4 3]
[5 7 7 3 7]


In [10]:
c=a+b     #broadcasting
print(c)

[ 7 14 14  7 10]


- 2 array ko mearg kr ke ek 1d array banana(but ye 2d array hi banata hai.)
- **vstack function**--------------verticla stack

In [11]:
d=np.vstack((a,b))          #abhi ye conbind hoke 2d array ban gya hai.
print(d)
print(d.ndim)

[[2 7 7 4 3]
 [5 7 7 3 7]]
2


- but hume concatenation krne ke , variable a and b ko **1d array** banana hai.
- **hstack function**--------horizental stack

In [12]:
e=np.hstack((a,b))
print(e)
print(e.ndim)

[2 7 7 4 3 5 7 7 3 7]
1


- 2 array ko concatenation krne ke liye 
- **concatenate function**

In [13]:
print(a)
print(b)

[2 7 7 4 3]
[5 7 7 3 7]


In [14]:
f=np.concatenate((a,b))
print(f)
print(f.ndim)

[2 7 7 4 3 5 7 7 3 7]
1


### - two matrix ko combind kr ke ,ek tisri matrix banane ke liye.



In [15]:
a=np.random.randint(1,9,(3,3))
b=np.random.randint(1,9,(3,3))
print(a)
print(b)

[[2 1 8]
 [3 2 2]
 [3 6 6]]
[[8 6 6]
 [2 2 1]
 [7 8 3]]


In [16]:
np.vstack((a,b))    #verticle stack me humari rows increase ho gai

array([[2, 1, 8],
       [3, 2, 2],
       [3, 6, 6],
       [8, 6, 6],
       [2, 2, 1],
       [7, 8, 3]])

In [17]:
np.hstack((a,b))    #horizontal stack me humari columns increase ho gaye

array([[2, 1, 8, 8, 6, 6],
       [3, 2, 2, 2, 2, 1],
       [3, 6, 6, 7, 8, 3]])

In [18]:
#axis=0 krne per as like vstack jaisa bana deta hai.---------default axis 0 hota hai.
np.concatenate((a,b),axis=0)    #concatenate me rows increase krta hai.   

array([[2, 1, 8],
       [3, 2, 2],
       [3, 6, 6],
       [8, 6, 6],
       [2, 2, 1],
       [7, 8, 3]])

In [19]:
#axis=1 krne per as like hstack jaisa bana deta hai.
np.concatenate((a,b),axis=1)   #concatenate me ab ye column increase kr dega.

array([[2, 1, 8, 8, 6, 6],
       [3, 2, 2, 2, 2, 1],
       [3, 6, 6, 7, 8, 3]])

In [20]:
#axis=None krne per , ye hume dono matrix ko 1d array me convert kr ke de deta hai.
np.concatenate((a,b),axis=None)

array([2, 1, 8, 3, 2, 2, 3, 6, 6, 8, 6, 6, 2, 2, 1, 7, 8, 3])

In [21]:
print(a)
print(b)

[[2 1 8]
 [3 2 2]
 [3 6 6]]
[[8 6 6]
 [2 2 1]
 [7 8 3]]


In [22]:
a=a.flatten()
print(a)

[2 1 8 3 2 2 3 6 6]


- **append function**
    - append fucntion do alag alag array ko convert krne ke liye hota hai.
    - append function se ek new array create hota hai.
    - ek array me kisi dusre array ko append krna.

In [23]:
g=np.append(a,5)
print(g)
print(g.dtype)

[2 1 8 3 2 2 3 6 6 5]
int32


In [25]:
g=np.append(a,500)
print(g)
print(g.dtype)

[  2   1   8   3   2   2   3   6   6 500]
int32


- **insert function**
    - kisi bhi exiting array ke ander , kisi bhi perticular index pe apni value ko **insert** kr skte hai.
    - ye new array banata hai.

In [26]:
print(g)

[  2   1   8   3   2   2   3   6   6 500]


In [27]:
a=np.insert(g,2,1000)
print(a)

[   2    1 1000    8    3    2    2    3    6    6  500]


In [28]:
a

array([   2,    1, 1000,    8,    3,    2,    2,    3,    6,    6,  500])

In [29]:
#ek sath multiple values ko bhi insert kr skte hai.
b=np.insert(a,4,[30,40,50,60,70,80,90])
print(b)

[   2    1 1000    8   30   40   50   60   70   80   90    3    2    2
    3    6    6  500]


- **delete function**
    - delete function se kisi bhi exiting array me, kisi bhi perticular indexd ki value ko **delete** kr skte hai.

In [30]:
print(b)

[   2    1 1000    8   30   40   50   60   70   80   90    3    2    2
    3    6    6  500]


In [31]:
d=np.delete(b,2)
print(d)

[  2   1   8  30  40  50  60  70  80  90   3   2   2   3   6   6 500]


In [32]:
#ek sath multiple values ko bhi delete kr skte hai.
print(d)
e=np.delete(d,[3,4,5,7])
print(e)

[  2   1   8  30  40  50  60  70  80  90   3   2   2   3   6   6 500]
[  2   1   8  60  80  90   3   2   2   3   6   6 500]


In [33]:
print(e)

[  2   1   8  60  80  90   3   2   2   3   6   6 500]


- **Array ko break krna**

In [34]:
print(a)

[   2    1 1000    8    3    2    2    3    6    6  500]


In [35]:
a1=a[0:5]
a2=a[6:-1]
print(a1)
print(a2)

[   2    1 1000    8    3]
[2 3 6 6]


- **vsplit function**-----------rows wise
- **hsplit function**-----------columns wise

In [47]:
a=np.random.randint(1,9,(3,4))
print(a)

[[5 3 7 1]
 [4 1 4 5]
 [8 1 4 2]]


In [50]:
np.vsplit(a,(3))

[array([[5, 3, 7, 1]]), array([[4, 1, 4, 5]]), array([[8, 1, 4, 2]])]

In [52]:
np.hsplit(a,4)

[array([[5],
        [4],
        [8]]),
 array([[3],
        [1],
        [1]]),
 array([[7],
        [4],
        [4]]),
 array([[1],
        [5],
        [2]])]